version: 2.1
orbs:
  slack: circleci/slack@3.4.2
defaults: &defaults
  docker:
    - image: circleci/python:3.6.4

commands:
  docker_build_n_test:
    description: "Reusable docker builds!"
    parameters:
      tag:
        type: string
        default: ""
      node_env:
        type: string
        default: "development"
    steps:
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS
      - run:
          name: Build the image
          command: docker build -t adludiodev/REPO_NAME<< parameters.tag >> .
      - run:
          name: Test the build
          command: 
            pip install --user --upgrade pip;
            pip install --user -r requirements.txt ;
            python -m pytest
  docker_push:
    description: "Push to docker"
    parameters:
      tag:
        type: string
        default: ""
    steps: 
      - run:
          name: Push the image
          command: docker push adludiodev/REPO_NAME<< parameters.tag >>
jobs:
  test:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - docker_build_n_test
  build_master:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - docker_build_n_test:
          tag: ":$CIRCLE_BUILD_NUM"
          node_env: "production"
      - docker_push:
          tag: ":$CIRCLE_BUILD_NUM"
      - run:
          name: Deploy the build
          command:
            >-
              docker run 
              -e AWS_DEFAULT_REGION=eu-central-1  
              -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
              -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
              -e CIRCLE_BUILD_NUM="$CIRCLE_BUILD_NUM" 
              -m 2500m
              silintl/ecs-deploy 
              -c NAME_OF_ECS_CLUSTER
              --use-latest-task-def
              -i adludiodev/REPO_NAME
              -n NAME_OF_ECS_SERVICE
              -e CIRCLE_BUILD_NUM 
              -t 600
      - slack/status: 
          success_message: ':shipitparrot: REPO_NAME.adludio.com was successfully deployed'
      
  build_release:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - docker_build_n_test:
          tag: ":$CIRCLE_TAG.$CIRCLE_BUILD_NUM"
          node_env: "production"
      - docker_push:
          tag: ":$CIRCLE_TAG.$CIRCLE_BUILD_NUM"
      - run:
          name: Deploy the build
          command: 
            >-
              docker run 
              -e AWS_DEFAULT_REGION=eu-central-1
              -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
              -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
              -e CIRCLE_TAG_AND_CIRCLE_BUILD_NUM="$CIRCLE_TAG.$CIRCLE_BUILD_NUM" 
              -m 2500m
              silintl/ecs-deploy
              -c NAME_OF_ECS_CLUSTER
              -i adludiodev/REPO_NAME 
              -n NAME_OF_ECS_SERVICE
              -e CIRCLE_TAG_AND_CIRCLE_BUILD_NUM 
              -t 600
      - slack/status: 
        success_message: ':shipitparrot: recengine.adludio.com was successfully deployed'


workflows:
  version: 2
  test:
    jobs:
      - test:
          context: adludio-robots
          filters:
            tags:
              ignore: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master
  build_master:
    jobs:
      - build_master:
          context: adludio-robots
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
  build_release:
    jobs:
      - build_release:
          context: adludio-robots
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/